# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FitbitBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup node
      uses: actions/setup-node@v1

    - name: Checkout Fitbit SDK
      run: npm add --dev @fitbit/sdk

    - name: Checkout Fitbit SDK-CLI
      run: npm add --dev @fitbit/sdk-cli

    - name: Run Build
      run: npx fitbit-build --if-present
